### ISSUE TITLE
gPRC 转换 Rest 的几种实现

### ISSUE THREAD

**Issue by jxlwqq** [jxlwqq/blog-microservices#1]

**Comment by jxlwqq** [comment]
Envoy Filter gRPC-JSON Transcoder Demo:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: myapp-grpc-transcoder
spec:
  workloadSelector:
    labels:
      app: myapp # match your deployment
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 50051 # application port
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.grpc_json_transcoder
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          services:
          - mycompany.myapi.v1.MyService # your gRPC service
          print_options:
            add_whitespace: true
            always_print_enums_as_ints: false
            always_print_primitive_fields: true
            preserve_proto_field_names: false
          convert_grpc_status: true
          proto_descriptor_bin: # base64 encoded proto descriptor
```

**Comment by jxlwqq** [comment]
本 demo 使用 gRPC Gateway，部分代码如下：


https://github.com/jxlwqq/blog-microservices/blob/541be8290929fc74dc51c368f7b38f169d120870/cmd/blog/main.go#L72-L87

**Comment by jxlwqq** [comment]
Kong 插件在 Kubernetes 集群的使用如下：

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: <grpc-gateway-example>
config: 
  proto: path/to/hello.proto
plugin: grpc-gateway
---
apiVersion: networking/v1beta1
kind: Ingress
metadata:
  name: {ROUTE}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: <grpc-gateway-example>
spec:
  rules:
  - host: examplehostname.com
    http:
      paths:
      - path: /bar
        backend:
          serviceName: echo
          servicePort: 80
```
